image: debian:latest

before_script:
    - apt-get update -qq && apt-get install -y -qq gnuradio-dev libcppunit-dev libpng++-dev libvorbis-dev libnova-dev cmake swig pkg-config build-essential 

test:
    script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr ..
        - make
        - make install
        - ldconfig
        - python -c "import satnogs"
        - rm -rf *
        - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DINCLUDE_DEBUG_BLOCKS=OFF -DCMAKE_INSTALL_PREFIX=/usr  ..
        - make
        - make install
        - ldconfig
        - python -c "import satnogs"
